implementation of generic worker
canonical/loki-worker-k8s-operator pull request #8
Opened 2024-07-20 03:18 UTC by Abuelodelanada

This PR uses the abstraction of the worker class in the Loki Worker charm.

# Testing Instructions (Before having a Coordinator using the generic coordinator lib)

```shell
# Pack the charm
$ charmcraft pack

# Deploy the charm
$ juju deploy ./*.charm worker --resource loki-image=docker.io/ubuntu/loki:3.0-22.04 --trust --config all=True
```

After that check the charm end up in `blocked` status:

```
Model  Controller  Cloud/Region        Version  SLA          Timestamp
loki   microk8s    microk8s/localhost  3.5.2    unsupported  00:16:49-03:00

App     Version  Status   Scale  Charm            Channel  Rev  Address         Exposed  Message
worker  3.0.0    blocked      1  loki-worker-k8s             0  10.152.183.200  no       Missing relation to a coordinator charm

Unit       Workload  Agent  Address     Ports  Message
worker/0*  blocked   idle   10.1.9.195         Missing relation to a coordinator charm
```

2024-07-25 08:43 UTC, lucabello commented
The way tracing is done has changed slightly, so that will need to be tweaked, but it's just a few lines :)

The rest is looking good, I'm eager to see the coordinator and the two charms together!

2024-07-29 08:31 UTC, lucabello requested changes

2024-07-29 08:31 UTC, lucabello commented on src/charm.py
> +            endpoints={"cluster": "loki-cluster", "tracing": "tracing"},
This likely needs to be changed, if you pull the latest `cos-lib` you'll see the "tracing" key isn't there anymore

2024-08-01 12:45 UTC, Abuelodelanada commented
Merging this very first version, so we can publish it to `edge` and use it for itest in loki-coordinator.
With this, we will be able to see this charm in action and discover things that should be improved/fixed.

2024-08-01 12:46 UTC, merged